version: "3.9"

services:
  frontend:
    build: ./pathwayer-frontend
    ports:
      - '3000:3000'
    volumes:
      - ./pathwayer-frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
  backend:
    build:
      context: ./pathwayer-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./pathwayer-backend/src:/usr/src/app/src
    environment:
      - port=8000
      - NODE_ENV=development
    depends_on:
      - postgres
    
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pathwayer
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  
  pg-admin:
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050

    ports:
      - "5050:5050"

volumes:
  data:
